<a href="https://colab.research.google.com/github/Mahesh0007/NumPy-Arrays-Operations/blob/main/numpy_scores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Task 1
np.random.seed(42)
scores = np.random.randint(50, 101, size=(5, 4))
print("Scores:\n", scores)

print("3rd student, 2nd subject:", scores[2, 1])
print("Last 2 students:\n", scores[3:, :])
print("First 3 students, subjects 2 and 3:\n", scores[:3, 1:3])


Scores:
 [[88 78 64 92]
 [57 70 88 68]
 [72 60 60 73]
 [85 89 73 52]
 [71 51 73 93]]
3rd student, 2nd subject: 60
Last 2 students:
 [[85 89 73 52]
 [71 51 73 93]]
First 3 students, subjects 2 and 3:
 [[78 64]
 [70 88]
 [60 60]]


In [ ]:
col_mean = np.round(np.mean(scores, axis=0), 2)
print("Column-wise mean:", col_mean)

curve = np.array([5, 3, 7, 2])
curved_scores = scores + curve
curved_scores = np.clip(curved_scores, None, 100)
print("Curved scores:\n", curved_scores)

row_max = np.max(curved_scores, axis=1)
print("Row-wise max:", row_max)

Column-wise mean: [74.6 69.6 71.6 75.6]
Curved scores:
 [[93 81 71 94]
 [62 73 95 70]
 [77 63 67 75]
 [90 92 80 54]
 [76 54 80 95]]
Row-wise max: [94 95 77 92 95]


In [ ]:
row_min = curved_scores.min(axis=1, keepdims=True)
row_max2 = curved_scores.max(axis=1, keepdims=True)
normalized = (curved_scores - row_min) / (row_max2 - row_min)
print("Normalized:\n", normalized)

idx = np.unravel_index(np.argmax(normalized), normalized.shape)
print("Student index:", idx[0], "Subject index:", idx[1])

above_90 = curved_scores[curved_scores > 90]
print("Scores strictly above 90:", above_90)

Normalized:
 [[0.95652174 0.43478261 0.         1.        ]
 [0.         0.33333333 1.         0.24242424]
 [1.         0.         0.28571429 0.85714286]
 [0.94736842 1.         0.68421053 0.        ]
 [0.53658537 0.         0.63414634 1.        ]]
Student index: 0 Subject index: 3
Scores strictly above 90: [93 94 95 92 95]
